### ISSUE TITLE
packaging?

### ISSUE THREAD

**Issue by marksantcroos** [vkkodali/cthreepo#1]
Hi @vkkodali,

Thanks for making and publishing this. I support the idea that not everyone roles their own!

Would it be an idea to turn it into a pypi package, or do you think that is overkill?

Cheers,

Mark

**Comment by vkkodali** [comment]
I love that idea. It's just that I have never created a package before. It's been on my to-do list for some time now. 
If you have such experience, I appreciate any contribution you can make.
