### ISSUE TITLE
upload to pypi

### ISSUE THREAD

**Issue by marksantcroos** [vkkodali/cthreepo#3]
Thanks for merging the PR :-)

Can you also upload to pypi?

Instructions are here: https://packaging.python.org/tutorials/packaging-projects/
The rough idea is that you create an account, create distribution archives and upload them.

The good news is that https://pypi.org/project/cthreepo/ is still available!

**Comment by marksantcroos** [comment]
In the meanwhile I've created a bioconda package at https://anaconda.org/bioconda/cthreepo, which also triggered a docker container build at https://quay.io/repository/biocontainers/cthreepo.

The conda package is now build using a git reference to this repo, it would still be better to have tags/versions here or a proper pypi package.

**Comment by vkkodali** [comment]
Apparently I managed to lose track of this ticket... Sorry about that. The package is in PyPi now: https://pypi.org/project/cthreepo/

**Comment by marksantcroos** [comment]
Thanks! I've now based the bioconda package of from pypi (https://github.com/bioconda/bioconda-recipes/commit/611a252225266e1b9837d2c3a20bd43ecb1e9355)
