### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by milaeri** [vkkodali/cthreepo#6]
Hi,
Thanks for creating this very helpful script. I'm having trouble running it, and was wondering if you help me pin point what the issue with my script. 

Here's the error I'm encountering: `+ python cthreepo.py
  
File "cthreepo.py", line 11
 
   --id_from rs \
               ^
SyntaxError: invalid syntax
`
here's my python script: 

`gpfs1/home/e/m/embueno/myscripts/cthreepo/ \

--infile /gpfs1/home/e/m/embueno/myscripts/cthreepo/test_files/lepdecOGSv12GCF0005003251.gff3 \

--id_from rs \

--id_to genbank \

--format gff3 \

--mapfile /gpfs1/home/e/m/embueno/myscripts/cthreepo/cthreepo/mapfiles/GCF_000500325.1_Ldec_2.0_assembly_report.txt \

--outfile lepdecOGSv12GCF0005003251GB.gff3
`
Thank you in advance.

E

**Comment by vkkodali** [comment]
How did you install `cthreepo`? I don't expect to see a file named `chtreepo.py`. Can you execute `cthreepo -h` and see if it returns help text? 
Though the error you are seeing is not related to this, `--id_to genbank` needs to be changed to `--id_to gb` for it to work.

**Comment by milaeri** [comment]
That might actually be the problem- i work on my uni's computing cluster, and just realized i need to ask for packages to be directly installed. The command `cthreepo -h` didn't work, which makes sense since its not currently installed in their list of packages. Anyway, once that's settled I will try again with `--id_to gb` 
Thanks 
E

**Comment by milaeri** [comment]
it worked after installing and changing the --id_to gb, thanks!

E
